export const theme = {
  colors: {
    surface: "#0b1326",
    "surface-container": "#171f33",
    "surface-container-low": "#131b2e",
    "surface-container-lowest": "#060e20",
    "surface-container-high": "#222a3d",
    "surface-container-highest": "#2d3449",
    "surface-bright": "#31394d",
    "surface-dim": "#0b1326",
    "surface-tint": "#bbc3ff",
    background: "#0b1326",
    primary: "#bbc3ff",
    "primary-container": "#001d92",
    "on-primary": "#001d93",
    "on-primary-container": "#7d8fff",
    "on-surface": "#dae2fd",
    "on-surface-variant": "#c6c5d4",
    secondary: "#94ccff",
    "secondary-container": "#0375b2",
    "on-secondary": "#003352",
    "on-secondary-container": "#eef5ff",
    tertiary: "#cdc1e5",
    "tertiary-container": "#342b48",
    "on-tertiary": "#342c49",
    "on-tertiary-container": "#9e92b5",
    error: "#ffb4ab",
    "error-container": "#93000a",
    "on-error": "#690005",
    "on-error-container": "#ffdad6",
    outline: "#908f9d",
    "outline-variant": "#454652",
  },
  fontFamily: {
    headline: ["Manrope", "sans-serif"],
    body: ["Inter", "sans-serif"],
    label: ["Inter", "sans-serif"],
  },
  borderRadius: {
    DEFAULT: "0.125rem",
    lg: "0.25rem",
    xl: "0.5rem",
    full: "0.75rem",
  },
};

export type Theme = typeof theme;