-- CreateTable
CREATE TABLE "PUSH_TOKEN" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "token" TEXT NOT NULL,
    "platform" TEXT NOT NULL DEFAULT 'expo',
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "lastSeenAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "userId" TEXT NOT NULL,
    "tenantId" TEXT NOT NULL,
    CONSTRAINT "PUSH_TOKEN_userId_fkey" FOREIGN KEY ("userId") REFERENCES "USER" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "PUSH_TOKEN_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "TENANT" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateIndex
CREATE UNIQUE INDEX "PUSH_TOKEN_token_key" ON "PUSH_TOKEN"("token");

-- CreateIndex
CREATE INDEX "PUSH_TOKEN_userId_idx" ON "PUSH_TOKEN"("userId");

-- CreateIndex
CREATE INDEX "PUSH_TOKEN_tenantId_idx" ON "PUSH_TOKEN"("tenantId");
