-- CreateTable
CREATE TABLE "TENANT" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "slug" TEXT NOT NULL,
    "logo" TEXT,
    "settings" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "TENANT_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "USER" (
    "id" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "avatar" TEXT,
    "role" TEXT NOT NULL DEFAULT 'MEMBER',
    "passwordHash" TEXT,
    "lastLoginAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "tenantId" TEXT NOT NULL,
    "teamId" TEXT,

    CONSTRAINT "USER_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "REP" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "email" TEXT,
    "avatar" TEXT,
    "title" TEXT,
    "department" TEXT,
    "hireDate" TIMESTAMP(3),
    "status" TEXT NOT NULL DEFAULT 'ACTIVE',
    "metadata" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "tenantId" TEXT NOT NULL,
    "teamId" TEXT,

    CONSTRAINT "REP_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "REP_SCORE" (
    "id" TEXT NOT NULL,
    "score" DOUBLE PRECISION NOT NULL,
    "confidence" DOUBLE PRECISION NOT NULL,
    "dimension" TEXT NOT NULL,
    "period" TEXT,
    "calculatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "repId" TEXT NOT NULL,
    "userId" TEXT,

    CONSTRAINT "REP_SCORE_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "TEAM" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "managerId" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "tenantId" TEXT NOT NULL,

    CONSTRAINT "TEAM_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "SESSION" (
    "id" TEXT NOT NULL,
    "type" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "summary" TEXT,
    "transcript" TEXT,
    "sentiment" DOUBLE PRECISION,
    "entities" TEXT,
    "metadata" TEXT,
    "startedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "endedAt" TIMESTAMP(3),
    "score" DOUBLE PRECISION,
    "flags" TEXT,
    "tenantId" TEXT NOT NULL,
    "repId" TEXT NOT NULL,
    "userId" TEXT,

    CONSTRAINT "SESSION_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ALERT" (
    "id" TEXT NOT NULL,
    "type" TEXT NOT NULL,
    "severity" TEXT NOT NULL DEFAULT 'INFO',
    "title" TEXT NOT NULL,
    "message" TEXT NOT NULL,
    "metadata" TEXT,
    "acknowledged" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "scoreDelta" DOUBLE PRECISION,
    "driver" TEXT,
    "tenantId" TEXT NOT NULL,
    "sessionId" TEXT,

    CONSTRAINT "ALERT_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "BENCHMARK" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "type" TEXT NOT NULL,
    "formula" TEXT,
    "thresholds" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "tenantId" TEXT NOT NULL,

    CONSTRAINT "BENCHMARK_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "CANDIDATE_LIST" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "source" TEXT,
    "candidates" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "tenantId" TEXT NOT NULL,

    CONSTRAINT "CANDIDATE_LIST_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "INTEGRATION" (
    "id" TEXT NOT NULL,
    "provider" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'INACTIVE',
    "config" TEXT,
    "lastSyncAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "tenantId" TEXT NOT NULL,

    CONSTRAINT "INTEGRATION_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "REVIEW_QUEUE" (
    "id" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'PENDING',
    "itemType" TEXT NOT NULL,
    "itemId" TEXT NOT NULL,
    "reviewType" TEXT NOT NULL,
    "notes" TEXT,
    "reviewedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "tenantId" TEXT NOT NULL,

    CONSTRAINT "REVIEW_QUEUE_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "PUSH_TOKEN" (
    "id" TEXT NOT NULL,
    "token" TEXT NOT NULL,
    "platform" TEXT NOT NULL DEFAULT 'expo',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "lastSeenAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "userId" TEXT NOT NULL,
    "tenantId" TEXT NOT NULL,

    CONSTRAINT "PUSH_TOKEN_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "PROVENANCE" (
    "id" TEXT NOT NULL,
    "source" TEXT NOT NULL,
    "sourceId" TEXT NOT NULL,
    "data" TEXT NOT NULL,
    "hash" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "tenantId" TEXT NOT NULL,

    CONSTRAINT "PROVENANCE_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "TENANT_slug_key" ON "TENANT"("slug");

-- CreateIndex
CREATE UNIQUE INDEX "USER_email_tenantId_key" ON "USER"("email", "tenantId");

-- CreateIndex
CREATE UNIQUE INDEX "REP_email_tenantId_key" ON "REP"("email", "tenantId");

-- CreateIndex
CREATE UNIQUE INDEX "PUSH_TOKEN_token_key" ON "PUSH_TOKEN"("token");

-- CreateIndex
CREATE INDEX "PUSH_TOKEN_userId_idx" ON "PUSH_TOKEN"("userId");

-- CreateIndex
CREATE INDEX "PUSH_TOKEN_tenantId_idx" ON "PUSH_TOKEN"("tenantId");

-- AddForeignKey
ALTER TABLE "USER" ADD CONSTRAINT "USER_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "TENANT"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "USER" ADD CONSTRAINT "USER_teamId_fkey" FOREIGN KEY ("teamId") REFERENCES "TEAM"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "REP" ADD CONSTRAINT "REP_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "TENANT"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "REP" ADD CONSTRAINT "REP_teamId_fkey" FOREIGN KEY ("teamId") REFERENCES "TEAM"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "REP_SCORE" ADD CONSTRAINT "REP_SCORE_repId_fkey" FOREIGN KEY ("repId") REFERENCES "REP"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "REP_SCORE" ADD CONSTRAINT "REP_SCORE_userId_fkey" FOREIGN KEY ("userId") REFERENCES "USER"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TEAM" ADD CONSTRAINT "TEAM_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "TENANT"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "SESSION" ADD CONSTRAINT "SESSION_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "TENANT"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "SESSION" ADD CONSTRAINT "SESSION_repId_fkey" FOREIGN KEY ("repId") REFERENCES "REP"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "SESSION" ADD CONSTRAINT "SESSION_userId_fkey" FOREIGN KEY ("userId") REFERENCES "USER"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ALERT" ADD CONSTRAINT "ALERT_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "TENANT"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ALERT" ADD CONSTRAINT "ALERT_sessionId_fkey" FOREIGN KEY ("sessionId") REFERENCES "SESSION"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "BENCHMARK" ADD CONSTRAINT "BENCHMARK_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "TENANT"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CANDIDATE_LIST" ADD CONSTRAINT "CANDIDATE_LIST_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "TENANT"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "INTEGRATION" ADD CONSTRAINT "INTEGRATION_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "TENANT"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "REVIEW_QUEUE" ADD CONSTRAINT "REVIEW_QUEUE_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "TENANT"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PUSH_TOKEN" ADD CONSTRAINT "PUSH_TOKEN_userId_fkey" FOREIGN KEY ("userId") REFERENCES "USER"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PUSH_TOKEN" ADD CONSTRAINT "PUSH_TOKEN_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "TENANT"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PROVENANCE" ADD CONSTRAINT "PROVENANCE_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "TENANT"("id") ON DELETE CASCADE ON UPDATE CASCADE;
