-- AlterTable
ALTER TABLE "ALERT" ADD COLUMN "driver" TEXT;
ALTER TABLE "ALERT" ADD COLUMN "scoreDelta" REAL;

-- AlterTable
ALTER TABLE "SESSION" ADD COLUMN "flags" TEXT;
ALTER TABLE "SESSION" ADD COLUMN "score" REAL;
